export const catalog = [
  {
    id: "mens-cotton-shirt",
    name: "Everyday Cotton Shirt",
    gender: "Men",
    category: "Shirts",
    price: 1890,
    fabric: "100% cotton",
    fit: "Relaxed",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Sand", "Taupe", "Black"],
    stock: 4,
    image: "images/men-1.webp",
    description:
      "Everyday Cotton Shirt brings a considered relaxed silhouette to your everyday wardrobe. Made with 100% cotton, it is easy to combine with your favourite essentials.",
    care: "Wash gently at 30\u00b0C with similar colours. Dry in the shade; avoid tumble drying. Check the garment label before ironing.",
    related: [
      "men-lightweight-linen-shirt",
      "men-oxford-cotton-shirt",
      "men-striped-linen-shirt",
    ],
    imageWidth: 362,
    imageHeight: 362,
    styling: "Pair with straight trousers, or wear open over a simple tee.",
  },
  {
    id: "men-essential-crew-neck-t-shirt",
    name: "Essential Crew-Neck T-Shirt",
    gender: "Men",
    category: "T-shirts",
    price: 790,
    fabric: "100% cotton",
    fit: "Regular",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Blue", "Black"],
    stock: 7,
    image: "images/men-2.webp",
    colorImages: {
      Blue: "images/men-essential-tee-blue.webp",
      Black: "images/men-2.webp",
    },
    description:
      "Essential Crew-Neck T-Shirt brings a considered regular silhouette to your everyday wardrobe. Made with 100% cotton, it is easy to combine with your favourite essentials.",
    care: "Wash gently at 30\u00b0C with similar colours. Dry in the shade; avoid tumble drying. Check the garment label before ironing.",
    related: [
      "men-textured-cotton-polo",
      "men-olive-everyday-crew-tee",
      "men-heavyweight-cotton-tee",
    ],
    imageWidth: 362,
    imageHeight: 362,
    styling: "Wear with denim, or layer beneath an open shirt or jacket.",
  },
  {
    id: "men-tailored-straight-fit-trousers",
    name: "Tailored Straight-Fit Trousers",
    gender: "Men",
    category: "Trousers",
    price: 2290,
    fabric: "98% cotton, 2% elastane",
    fit: "Straight",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Blue", "Black"],
    stock: 10,
    image: "images/men-3.webp",
    description:
      "Tailored Straight-Fit Trousers brings a considered straight silhouette to your everyday wardrobe. Made with 98% cotton, 2% elastane, it is easy to combine with your favourite essentials.",
    care: "Wash gently at 30\u00b0C with similar colours. Dry in the shade; avoid tumble drying. Check the garment label before ironing.",
    related: [
      "men-pleated-tailored-trousers",
      "men-tapered-cotton-chinos",
      "men-relaxed-weekend-chinos",
    ],
    imageWidth: 362,
    imageHeight: 362,
    styling:
      "Combine with a simple shirt or tucked top; check the seated waist fit.",
  },
  {
    id: "men-classic-denim-jacket",
    name: "Classic Denim Jacket",
    gender: "Men",
    category: "Jackets",
    price: 3490,
    fabric: "100% cotton denim",
    fit: "Regular",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Sand", "Taupe", "Black"],
    stock: 13,
    image: "images/men-4.webp",
    description:
      "Classic Denim Jacket brings a considered regular silhouette to your everyday wardrobe. Made with 100% cotton denim, it is easy to combine with your favourite essentials.",
    care: "Wash gently at 30\u00b0C with similar colours. Dry in the shade; avoid tumble drying. Check the garment label before ironing.",
    related: [
      "men-lightweight-bomber-jacket",
      "men-cotton-chore-jacket",
      "men-quilted-everyday-jacket",
    ],
    imageWidth: 362,
    imageHeight: 362,
    styling:
      "Layer over a tee, shirt, or light knit with room through the shoulders.",
  },
  {
    id: "men-lightweight-linen-shirt",
    name: "Lightweight Linen Shirt",
    gender: "Men",
    category: "Shirts",
    price: 2490,
    fabric: "100% linen",
    fit: "Relaxed",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Blue", "Black"],
    stock: 16,
    image: "images/men-5.webp",
    description:
      "Lightweight Linen Shirt brings a considered relaxed silhouette to your everyday wardrobe. Made with 100% linen, it is easy to combine with your favourite essentials.",
    care: "Wash gently at 30\u00b0C with similar colours. Dry in the shade; avoid tumble drying. Check the garment label before ironing.",
    related: [
      "mens-cotton-shirt",
      "men-oxford-cotton-shirt",
      "men-striped-linen-shirt",
    ],
    imageWidth: 362,
    imageHeight: 362,
    styling: "Pair with straight trousers, or wear open over a simple tee.",
  },
  {
    id: "men-relaxed-knit-pullover",
    name: "Relaxed Knit Pullover",
    gender: "Men",
    category: "Knitwear",
    price: 2690,
    fabric: "80% cotton, 20% wool",
    fit: "Relaxed",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Blue", "Black"],
    stock: 19,
    image: "images/men-6.webp",
    description:
      "Relaxed Knit Pullover brings a considered relaxed silhouette to your everyday wardrobe. Made with 80% cotton, 20% wool, it is easy to combine with your favourite essentials.",
    care: "Wash gently at 30\u00b0C with similar colours. Dry in the shade; avoid tumble drying. Check the garment label before ironing.",
    related: [
      "men-cable-knit-cotton-sweater",
      "men-soft-v-neck-knit",
      "men-zip-neck-knit-pullover",
    ],
    imageWidth: 362,
    imageHeight: 362,
    styling:
      "Add texture over a simple base. Fold between wears to help retain shape.",
  },
  {
    id: "men-everyday-straight-jeans",
    name: "Everyday Straight Jeans",
    gender: "Men",
    category: "Denim",
    price: 2390,
    fabric: "99% cotton, 1% elastane",
    fit: "Straight",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Sand", "Taupe", "Black"],
    stock: 22,
    image: "images/men-7.webp",
    description:
      "Everyday Straight Jeans brings a considered straight silhouette to your everyday wardrobe. Made with 99% cotton, 1% elastane, it is easy to combine with your favourite essentials.",
    care: "Wash gently at 30\u00b0C with similar colours. Dry in the shade; avoid tumble drying. Check the garment label before ironing.",
    related: [
      "men-dark-indigo-slim-jeans",
      "men-light-wash-relaxed-jeans",
      "men-black-straight-leg-jeans",
    ],
    imageWidth: 362,
    imageHeight: 362,
    styling:
      "Combine with cotton basics and textured layers. Compare the rise and leg shape.",
  },
  {
    id: "men-performance-training-tee",
    name: "Performance Training Tee",
    gender: "Men",
    category: "Activewear",
    price: 1290,
    fabric: "90% polyester, 10% elastane",
    fit: "Athletic",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Blue", "Black"],
    stock: 25,
    image: "images/men-8.webp",
    description:
      "Performance Training Tee brings a considered athletic silhouette to your everyday wardrobe. Made with 90% polyester, 10% elastane, it is easy to combine with your favourite essentials.",
    care: "Wash gently at 30\u00b0C with similar colours. Dry in the shade; avoid tumble drying. Check the garment label before ironing.",
    related: [
      "men-everyday-training-joggers",
      "men-lightweight-training-shorts",
      "men-performance-zip-jacket",
    ],
    imageWidth: 362,
    imageHeight: 362,
    styling:
      "Combine with comfortable training separates and allow room for movement.",
  },
  {
    id: "men-modern-tailored-blazer",
    name: "Modern Tailored Blazer",
    gender: "Men",
    category: "Formal wear",
    price: 4990,
    fabric: "70% polyester, 30% viscose",
    fit: "Tailored",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Blue", "Black"],
    stock: 28,
    image: "images/men-9.webp",
    colorImages: {
      Blue: "images/men-modern-blazer-blue.webp",
      Black: "images/men-9.webp",
    },
    description:
      "Modern Tailored Blazer brings a considered tailored silhouette to your everyday wardrobe. Made with 70% polyester, 30% viscose, it is easy to combine with your favourite essentials.",
    care: "Wash gently at 30\u00b0C with similar colours. Dry in the shade; avoid tumble drying. Check the garment label before ironing.",
    related: [
      "men-evening-formal-trousers",
      "men-tailored-occasion-waistcoat",
      "men-modern-two-piece-suit",
    ],
    imageWidth: 362,
    imageHeight: 362,
    styling:
      "Choose clean layers for occasions. Check shoulders, waist, and garment length.",
  },
  {
    id: "men-textured-cotton-polo",
    name: "Textured Cotton Polo",
    gender: "Men",
    category: "T-shirts",
    price: 1490,
    fabric: "100% cotton",
    fit: "Regular",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Sand", "Taupe", "Black"],
    stock: 31,
    image: "images/men-10.webp",
    description:
      "Textured Cotton Polo brings a considered regular silhouette to your everyday wardrobe. Made with 100% cotton, it is easy to combine with your favourite essentials.",
    care: "Wash gently at 30\u00b0C with similar colours. Dry in the shade; avoid tumble drying. Check the garment label before ironing.",
    related: [
      "men-essential-crew-neck-t-shirt",
      "men-olive-everyday-crew-tee",
      "men-heavyweight-cotton-tee",
    ],
    imageWidth: 362,
    imageHeight: 362,
    styling: "Wear with denim, or layer beneath an open shirt or jacket.",
  },
  {
    id: "men-lightweight-bomber-jacket",
    name: "Lightweight Bomber Jacket",
    gender: "Men",
    category: "Jackets",
    price: 3290,
    fabric: "100% nylon",
    fit: "Regular",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Blue", "Black"],
    stock: 34,
    image: "images/men-11.webp",
    description:
      "Lightweight Bomber Jacket brings a considered regular silhouette to your everyday wardrobe. Made with 100% nylon, it is easy to combine with your favourite essentials.",
    care: "Wash gently at 30\u00b0C with similar colours. Dry in the shade; avoid tumble drying. Check the garment label before ironing.",
    related: [
      "men-classic-denim-jacket",
      "men-cotton-chore-jacket",
      "men-quilted-everyday-jacket",
    ],
    imageWidth: 362,
    imageHeight: 362,
    styling:
      "Layer over a tee, shirt, or light knit with room through the shoulders.",
  },
  {
    id: "men-evening-formal-trousers",
    name: "Evening Formal Trousers",
    gender: "Men",
    category: "Formal wear",
    price: 2890,
    fabric: "70% polyester, 30% viscose",
    fit: "Tailored",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Blue", "Black"],
    stock: 37,
    image: "images/men-12.webp",
    description:
      "Evening Formal Trousers brings a considered tailored silhouette to your everyday wardrobe. Made with 70% polyester, 30% viscose, it is easy to combine with your favourite essentials.",
    care: "Wash gently at 30\u00b0C with similar colours. Dry in the shade; avoid tumble drying. Check the garment label before ironing.",
    related: [
      "men-modern-tailored-blazer",
      "men-tailored-occasion-waistcoat",
      "men-modern-two-piece-suit",
    ],
    imageWidth: 362,
    imageHeight: 362,
    styling:
      "Choose clean layers for occasions. Check shoulders, waist, and garment length.",
  },
  {
    id: "women-everyday-midi-dress",
    name: "Everyday Midi Dress",
    gender: "Women",
    category: "Dresses",
    price: 2890,
    fabric: "100% cotton",
    fit: "Relaxed",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Sand", "Taupe", "Black"],
    stock: 4,
    image: "images/women-1-hq.webp",
    description:
      "Everyday Midi Dress brings a considered relaxed silhouette to your everyday wardrobe. Made with 100% cotton, it is easy to combine with your favourite essentials.",
    care: "Wash gently at 30\u00b0C with similar colours. Dry in the shade; avoid tumble drying. Check the garment label before ironing.",
    related: [
      "women-evening-satin-dress",
      "women-floral-everyday-midi-dress",
      "women-classic-wrap-dress",
    ],
    imageWidth: 1254,
    imageHeight: 1254,
    styling:
      "Wear simply for daytime or add a layer for evenings. Check bust, waist, and hip fit.",
  },
  {
    id: "women-soft-cotton-wrap-top",
    name: "Soft Cotton Wrap Top",
    gender: "Women",
    category: "Tops",
    price: 1490,
    fabric: "100% cotton",
    fit: "Regular",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Rose", "Taupe"],
    stock: 7,
    image: "images/women-2-hq.webp",
    description:
      "Soft Cotton Wrap Top brings a considered regular silhouette to your everyday wardrobe. Made with 100% cotton, it is easy to combine with your favourite essentials.",
    care: "Wash gently at 30\u00b0C with similar colours. Dry in the shade; avoid tumble drying. Check the garment label before ironing.",
    related: [
      "women-soft-cotton-poplin-blouse",
      "women-essential-cotton-t-shirt",
      "women-cotton-puff-sleeve-blouse",
    ],
    imageWidth: 1254,
    imageHeight: 1254,
    styling:
      "Pair with denim or tailored trousers for an adaptable combination.",
  },
  {
    id: "women-modern-linen-co-ord-set",
    name: "Modern Linen Co-ord Set",
    gender: "Women",
    category: "Co-ord sets",
    price: 3990,
    fabric: "100% linen",
    fit: "Relaxed",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Rose", "Taupe"],
    stock: 10,
    image: "images/women-3-hq.webp",
    description:
      "Modern Linen Co-ord Set brings a considered relaxed silhouette to your everyday wardrobe. Made with 100% linen, it is easy to combine with your favourite essentials.",
    care: "Wash gently at 30\u00b0C with similar colours. Dry in the shade; avoid tumble drying. Check the garment label before ironing.",
    related: [
      "women-linen-weekend-co-ord",
      "women-cotton-everyday-co-ord",
      "women-soft-knit-co-ord-set",
    ],
    imageWidth: 1254,
    imageHeight: 1254,
    styling:
      "Wear the pieces together, or combine each separate with wardrobe favourites.",
  },
  {
    id: "women-high-rise-straight-jeans",
    name: "High-Rise Straight Jeans",
    gender: "Women",
    category: "Denim",
    price: 2490,
    fabric: "99% cotton, 1% elastane",
    fit: "Straight",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Sand", "Taupe", "Black"],
    stock: 13,
    image: "images/women-4-hq.webp",
    description:
      "High-Rise Straight Jeans brings a considered straight silhouette to your everyday wardrobe. Made with 99% cotton, 1% elastane, it is easy to combine with your favourite essentials.",
    care: "Wash gently at 30\u00b0C with similar colours. Dry in the shade; avoid tumble drying. Check the garment label before ironing.",
    related: ["women-wide-leg-indigo-jeans"],
    imageWidth: 1254,
    imageHeight: 1254,
    styling:
      "Combine with cotton basics and textured layers. Compare the rise and leg shape.",
  },
  {
    id: "women-printed-everyday-kurta",
    name: "Printed Everyday Kurta",
    gender: "Women",
    category: "Ethnic wear",
    price: 1990,
    fabric: "100% cotton",
    fit: "Relaxed",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Rose", "Taupe"],
    stock: 16,
    image: "images/women-5.webp",
    description:
      "Printed Everyday Kurta brings a considered relaxed silhouette to your everyday wardrobe. Made with 100% cotton, it is easy to combine with your favourite essentials.",
    care: "Wash gently at 30\u00b0C with similar colours. Dry in the shade; avoid tumble drying. Check the garment label before ironing.",
    related: [
      "women-embroidered-cotton-kurta",
      "women-classic-straight-kurta",
      "women-sage-printed-kurta",
    ],
    imageWidth: 362,
    imageHeight: 362,
    styling: "Pair with comfortable trousers and understated accessories.",
  },
  {
    id: "women-relaxed-knit-cardigan",
    name: "Relaxed Knit Cardigan",
    gender: "Women",
    category: "Knitwear",
    price: 2790,
    fabric: "80% cotton, 20% wool",
    fit: "Relaxed",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Rose", "Taupe"],
    stock: 19,
    image: "images/women-6.webp",
    description:
      "Relaxed Knit Cardigan brings a considered relaxed silhouette to your everyday wardrobe. Made with 80% cotton, 20% wool, it is easy to combine with your favourite essentials.",
    care: "Wash gently at 30\u00b0C with similar colours. Dry in the shade; avoid tumble drying. Check the garment label before ironing.",
    related: [
      "women-soft-ribbed-sweater",
      "women-cable-knit-cardigan",
      "women-soft-sleeveless-knit-vest",
    ],
    imageWidth: 362,
    imageHeight: 362,
    styling:
      "Add texture over a simple base. Fold between wears to help retain shape.",
  },
  {
    id: "women-everyday-active-leggings",
    name: "Everyday Active Leggings",
    gender: "Women",
    category: "Activewear",
    price: 1590,
    fabric: "85% polyester, 15% elastane",
    fit: "Fitted",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Sand", "Taupe", "Black"],
    stock: 22,
    image: "images/women-7.webp",
    description:
      "Everyday Active Leggings brings a considered fitted silhouette to your everyday wardrobe. Made with 85% polyester, 15% elastane, it is easy to combine with your favourite essentials.",
    care: "Wash gently at 30\u00b0C with similar colours. Dry in the shade; avoid tumble drying. Check the garment label before ironing.",
    related: [
      "women-lightweight-training-jacket",
      "women-soft-performance-training-tee",
      "women-everyday-training-joggers",
    ],
    imageWidth: 362,
    imageHeight: 362,
    styling:
      "Combine with comfortable training separates and allow room for movement.",
  },
  {
    id: "women-soft-cotton-poplin-blouse",
    name: "Soft Cotton Poplin Blouse",
    gender: "Women",
    category: "Tops",
    price: 1790,
    fabric: "100% cotton",
    fit: "Regular",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Rose", "Taupe"],
    stock: 25,
    image: "images/women-8.webp",
    description:
      "Soft Cotton Poplin Blouse brings a considered regular silhouette to your everyday wardrobe. Made with 100% cotton, it is easy to combine with your favourite essentials.",
    care: "Wash gently at 30\u00b0C with similar colours. Dry in the shade; avoid tumble drying. Check the garment label before ironing.",
    related: [
      "women-soft-cotton-wrap-top",
      "women-essential-cotton-t-shirt",
      "women-cotton-puff-sleeve-blouse",
    ],
    imageWidth: 362,
    imageHeight: 362,
    styling:
      "Pair with denim or tailored trousers for an adaptable combination.",
  },
  {
    id: "women-evening-satin-dress",
    name: "Evening Satin Dress",
    gender: "Women",
    category: "Dresses",
    price: 3490,
    fabric: "100% viscose",
    fit: "Fluid",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Rose", "Taupe"],
    stock: 28,
    image: "images/women-9.webp",
    description:
      "Evening Satin Dress brings a considered fluid silhouette to your everyday wardrobe. Made with 100% viscose, it is easy to combine with your favourite essentials.",
    care: "Wash gently at 30\u00b0C with similar colours. Dry in the shade; avoid tumble drying. Check the garment label before ironing.",
    related: [
      "women-everyday-midi-dress",
      "women-floral-everyday-midi-dress",
      "women-classic-wrap-dress",
    ],
    imageWidth: 362,
    imageHeight: 362,
    styling:
      "Wear simply for daytime or add a layer for evenings. Check bust, waist, and hip fit.",
  },
  {
    id: "women-tailored-wide-leg-trousers",
    name: "Tailored Wide-Leg Trousers",
    gender: "Women",
    category: "Trousers",
    price: 2490,
    fabric: "70% polyester, 30% viscose",
    fit: "Wide leg",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Sand", "Taupe", "Black"],
    stock: 31,
    image: "images/women-10.webp",
    description:
      "Tailored Wide-Leg Trousers brings a considered wide leg silhouette to your everyday wardrobe. Made with 70% polyester, 30% viscose, it is easy to combine with your favourite essentials.",
    care: "Wash gently at 30\u00b0C with similar colours. Dry in the shade; avoid tumble drying. Check the garment label before ironing.",
    related: ["women-straight-leg-cotton-trousers"],
    imageWidth: 362,
    imageHeight: 362,
    styling:
      "Combine with a simple shirt or tucked top; check the seated waist fit.",
  },
  {
    id: "women-essential-cotton-t-shirt",
    name: "Essential Cotton T-Shirt",
    gender: "Women",
    category: "Tops",
    price: 890,
    fabric: "100% cotton",
    fit: "Regular",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Rose", "Taupe"],
    stock: 34,
    image: "images/women-11.webp",
    description:
      "Essential Cotton T-Shirt brings a considered regular silhouette to your everyday wardrobe. Made with 100% cotton, it is easy to combine with your favourite essentials.",
    care: "Wash gently at 30\u00b0C with similar colours. Dry in the shade; avoid tumble drying. Check the garment label before ironing.",
    related: [
      "women-soft-cotton-wrap-top",
      "women-soft-cotton-poplin-blouse",
      "women-cotton-puff-sleeve-blouse",
    ],
    imageWidth: 362,
    imageHeight: 362,
    styling:
      "Pair with denim or tailored trousers for an adaptable combination.",
  },
  {
    id: "women-soft-ribbed-sweater",
    name: "Soft Ribbed Sweater",
    gender: "Women",
    category: "Knitwear",
    price: 2390,
    fabric: "100% cotton",
    fit: "Relaxed",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Rose", "Taupe"],
    stock: 37,
    image: "images/women-12.webp",
    description:
      "Soft Ribbed Sweater brings a considered relaxed silhouette to your everyday wardrobe. Made with 100% cotton, it is easy to combine with your favourite essentials.",
    care: "Wash gently at 30\u00b0C with similar colours. Dry in the shade; avoid tumble drying. Check the garment label before ironing.",
    related: [
      "women-relaxed-knit-cardigan",
      "women-cable-knit-cardigan",
      "women-soft-sleeveless-knit-vest",
    ],
    imageWidth: 362,
    imageHeight: 362,
    styling:
      "Add texture over a simple base. Fold between wears to help retain shape.",
  },
  {
    id: "men-oxford-cotton-shirt",
    name: "Oxford Cotton Shirt",
    gender: "Men",
    category: "Shirts",
    price: 2190,
    fabric: "100% cotton",
    fit: "Regular",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Blue", "Taupe"],
    stock: 22,
    image: "images/men-oxford-cotton-shirt.webp",
    description:
      "Oxford Cotton Shirt brings a regular silhouette and considered texture to your everyday wardrobe. Made with 100% cotton, it pairs easily with your existing essentials.",
    care: "Wash gently according to the garment label. Use similar colours, reshape while damp, and dry in the shade. Tailored suits and waistcoats may require professional cleaning.",
    related: [
      "mens-cotton-shirt",
      "men-lightweight-linen-shirt",
      "men-striped-linen-shirt",
    ],
    imageWidth: 632,
    imageHeight: 392,
    styling: "Pair with straight trousers, or wear open over a simple tee.",
  },
  {
    id: "men-striped-linen-shirt",
    name: "Striped Linen Shirt",
    gender: "Men",
    category: "Shirts",
    price: 2690,
    fabric: "100% linen",
    fit: "Relaxed",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Taupe", "Blue"],
    stock: 23,
    image: "images/men-striped-linen-shirt.webp",
    description:
      "Striped Linen Shirt brings a relaxed silhouette and considered texture to your everyday wardrobe. Made with 100% linen, it pairs easily with your existing essentials.",
    care: "Wash gently according to the garment label. Use similar colours, reshape while damp, and dry in the shade. Tailored suits and waistcoats may require professional cleaning.",
    related: [
      "mens-cotton-shirt",
      "men-lightweight-linen-shirt",
      "men-oxford-cotton-shirt",
    ],
    imageWidth: 633,
    imageHeight: 392,
    styling: "Pair with straight trousers, or wear open over a simple tee.",
  },
  {
    id: "men-olive-everyday-crew-tee",
    name: "Olive Everyday Crew Tee",
    gender: "Men",
    category: "T-shirts",
    price: 890,
    fabric: "100% cotton",
    fit: "Regular",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Olive", "Black"],
    stock: 24,
    image: "images/men-olive-everyday-crew-tee.webp",
    description:
      "Olive Everyday Crew Tee brings a regular silhouette and considered texture to your everyday wardrobe. Made with 100% cotton, it pairs easily with your existing essentials.",
    care: "Wash gently according to the garment label. Use similar colours, reshape while damp, and dry in the shade. Tailored suits and waistcoats may require professional cleaning.",
    related: [
      "men-essential-crew-neck-t-shirt",
      "men-textured-cotton-polo",
      "men-heavyweight-cotton-tee",
    ],
    imageWidth: 632,
    imageHeight: 387,
    styling: "Wear with denim, or layer beneath an open shirt or jacket.",
  },
  {
    id: "men-heavyweight-cotton-tee",
    name: "Heavyweight Cotton Tee",
    gender: "Men",
    category: "T-shirts",
    price: 1190,
    fabric: "100% cotton",
    fit: "Relaxed",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Taupe", "Black"],
    stock: 25,
    image: "images/men-heavyweight-cotton-tee.webp",
    description:
      "Heavyweight Cotton Tee brings a relaxed silhouette and considered texture to your everyday wardrobe. Made with 100% cotton, it pairs easily with your existing essentials.",
    care: "Wash gently according to the garment label. Use similar colours, reshape while damp, and dry in the shade. Tailored suits and waistcoats may require professional cleaning.",
    related: [
      "men-essential-crew-neck-t-shirt",
      "men-textured-cotton-polo",
      "men-olive-everyday-crew-tee",
    ],
    imageWidth: 633,
    imageHeight: 387,
    styling: "Wear with denim, or layer beneath an open shirt or jacket.",
  },
  {
    id: "men-pleated-tailored-trousers",
    name: "Pleated Tailored Trousers",
    gender: "Men",
    category: "Trousers",
    price: 2790,
    fabric: "70% polyester, 30% viscose",
    fit: "Tailored",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Charcoal", "Black"],
    stock: 26,
    image: "images/men-pleated-tailored-trousers.webp",
    description:
      "Pleated Tailored Trousers brings a tailored silhouette and considered texture to your everyday wardrobe. Made with 70% polyester, 30% viscose, it pairs easily with your existing essentials.",
    care: "Wash gently according to the garment label. Use similar colours, reshape while damp, and dry in the shade. Tailored suits and waistcoats may require professional cleaning.",
    related: [
      "men-tailored-straight-fit-trousers",
      "men-tapered-cotton-chinos",
      "men-relaxed-weekend-chinos",
    ],
    imageWidth: 632,
    imageHeight: 465,
    styling:
      "Combine with a simple shirt or tucked top; check the seated waist fit.",
  },
  {
    id: "men-tapered-cotton-chinos",
    name: "Tapered Cotton Chinos",
    gender: "Men",
    category: "Trousers",
    price: 2390,
    fabric: "98% cotton, 2% elastane",
    fit: "Tapered",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Navy", "Sand"],
    stock: 27,
    image: "images/men-tapered-cotton-chinos.webp",
    description:
      "Tapered Cotton Chinos brings a tapered silhouette and considered texture to your everyday wardrobe. Made with 98% cotton, 2% elastane, it pairs easily with your existing essentials.",
    care: "Wash gently according to the garment label. Use similar colours, reshape while damp, and dry in the shade. Tailored suits and waistcoats may require professional cleaning.",
    related: [
      "men-tailored-straight-fit-trousers",
      "men-pleated-tailored-trousers",
      "men-relaxed-weekend-chinos",
    ],
    imageWidth: 633,
    imageHeight: 465,
    styling:
      "Combine with a simple shirt or tucked top; check the seated waist fit.",
  },
  {
    id: "men-relaxed-weekend-chinos",
    name: "Relaxed Weekend Chinos",
    gender: "Men",
    category: "Trousers",
    price: 2190,
    fabric: "100% cotton",
    fit: "Relaxed",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Sand", "Olive"],
    stock: 28,
    image: "images/men-relaxed-weekend-chinos.webp",
    description:
      "Relaxed Weekend Chinos brings a relaxed silhouette and considered texture to your everyday wardrobe. Made with 100% cotton, it pairs easily with your existing essentials.",
    care: "Wash gently according to the garment label. Use similar colours, reshape while damp, and dry in the shade. Tailored suits and waistcoats may require professional cleaning.",
    related: [
      "men-tailored-straight-fit-trousers",
      "men-pleated-tailored-trousers",
      "men-tapered-cotton-chinos",
    ],
    imageWidth: 643,
    imageHeight: 408,
    styling:
      "Combine with a simple shirt or tucked top; check the seated waist fit.",
  },
  {
    id: "men-dark-indigo-slim-jeans",
    name: "Dark Indigo Slim Jeans",
    gender: "Men",
    category: "Denim",
    price: 2690,
    fabric: "99% cotton, 1% elastane",
    fit: "Slim",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Indigo", "Black"],
    stock: 29,
    image: "images/men-dark-indigo-slim-jeans.webp",
    description:
      "Dark Indigo Slim Jeans brings a slim silhouette and considered texture to your everyday wardrobe. Made with 99% cotton, 1% elastane, it pairs easily with your existing essentials.",
    care: "Wash gently according to the garment label. Use similar colours, reshape while damp, and dry in the shade. Tailored suits and waistcoats may require professional cleaning.",
    related: [
      "men-everyday-straight-jeans",
      "men-light-wash-relaxed-jeans",
      "men-black-straight-leg-jeans",
    ],
    imageWidth: 643,
    imageHeight: 408,
    styling:
      "Combine with cotton basics and textured layers. Compare the rise and leg shape.",
  },
  {
    id: "men-light-wash-relaxed-jeans",
    name: "Light-Wash Relaxed Jeans",
    gender: "Men",
    category: "Denim",
    price: 2590,
    fabric: "100% cotton denim",
    fit: "Relaxed",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Blue", "Taupe"],
    stock: 30,
    image: "images/men-light-wash-relaxed-jeans.webp",
    description:
      "Light-Wash Relaxed Jeans brings a relaxed silhouette and considered texture to your everyday wardrobe. Made with 100% cotton denim, it pairs easily with your existing essentials.",
    care: "Wash gently according to the garment label. Use similar colours, reshape while damp, and dry in the shade. Tailored suits and waistcoats may require professional cleaning.",
    related: [
      "men-everyday-straight-jeans",
      "men-dark-indigo-slim-jeans",
      "men-black-straight-leg-jeans",
    ],
    imageWidth: 643,
    imageHeight: 407,
    styling:
      "Combine with cotton basics and textured layers. Compare the rise and leg shape.",
  },
  {
    id: "men-black-straight-leg-jeans",
    name: "Black Straight-Leg Jeans",
    gender: "Men",
    category: "Denim",
    price: 2490,
    fabric: "99% cotton, 1% elastane",
    fit: "Straight",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Indigo"],
    stock: 31,
    image: "images/men-black-straight-leg-jeans.webp",
    description:
      "Black Straight-Leg Jeans brings a straight silhouette and considered texture to your everyday wardrobe. Made with 99% cotton, 1% elastane, it pairs easily with your existing essentials.",
    care: "Wash gently according to the garment label. Use similar colours, reshape while damp, and dry in the shade. Tailored suits and waistcoats may require professional cleaning.",
    related: [
      "men-everyday-straight-jeans",
      "men-dark-indigo-slim-jeans",
      "men-light-wash-relaxed-jeans",
    ],
    imageWidth: 643,
    imageHeight: 407,
    styling:
      "Combine with cotton basics and textured layers. Compare the rise and leg shape.",
  },
  {
    id: "men-cotton-chore-jacket",
    name: "Cotton Chore Jacket",
    gender: "Men",
    category: "Jackets",
    price: 3790,
    fabric: "100% cotton",
    fit: "Regular",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Camel", "Olive"],
    stock: 32,
    image: "images/men-cotton-chore-jacket.webp",
    description:
      "Cotton Chore Jacket brings a regular silhouette and considered texture to your everyday wardrobe. Made with 100% cotton, it pairs easily with your existing essentials.",
    care: "Wash gently according to the garment label. Use similar colours, reshape while damp, and dry in the shade. Tailored suits and waistcoats may require professional cleaning.",
    related: [
      "men-classic-denim-jacket",
      "men-lightweight-bomber-jacket",
      "men-quilted-everyday-jacket",
    ],
    imageWidth: 643,
    imageHeight: 408,
    styling:
      "Layer over a tee, shirt, or light knit with room through the shoulders.",
  },
  {
    id: "men-quilted-everyday-jacket",
    name: "Quilted Everyday Jacket",
    gender: "Men",
    category: "Jackets",
    price: 4290,
    fabric: "100% polyester",
    fit: "Regular",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Navy", "Black"],
    stock: 33,
    image: "images/men-quilted-everyday-jacket.webp",
    description:
      "Quilted Everyday Jacket brings a regular silhouette and considered texture to your everyday wardrobe. Made with 100% polyester, it pairs easily with your existing essentials.",
    care: "Wash gently according to the garment label. Use similar colours, reshape while damp, and dry in the shade. Tailored suits and waistcoats may require professional cleaning.",
    related: [
      "men-classic-denim-jacket",
      "men-lightweight-bomber-jacket",
      "men-cotton-chore-jacket",
    ],
    imageWidth: 643,
    imageHeight: 408,
    styling:
      "Layer over a tee, shirt, or light knit with room through the shoulders.",
  },
  {
    id: "men-cable-knit-cotton-sweater",
    name: "Cable-Knit Cotton Sweater",
    gender: "Men",
    category: "Knitwear",
    price: 2990,
    fabric: "100% cotton",
    fit: "Regular",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Taupe", "Sand"],
    stock: 34,
    image: "images/men-cable-knit-cotton-sweater.webp",
    description:
      "Cable-Knit Cotton Sweater brings a regular silhouette and considered texture to your everyday wardrobe. Made with 100% cotton, it pairs easily with your existing essentials.",
    care: "Wash gently according to the garment label. Use similar colours, reshape while damp, and dry in the shade. Tailored suits and waistcoats may require professional cleaning.",
    related: [
      "men-relaxed-knit-pullover",
      "men-soft-v-neck-knit",
      "men-zip-neck-knit-pullover",
    ],
    imageWidth: 646,
    imageHeight: 383,
    styling:
      "Add texture over a simple base. Fold between wears to help retain shape.",
  },
  {
    id: "men-soft-v-neck-knit",
    name: "Soft V-Neck Knit",
    gender: "Men",
    category: "Knitwear",
    price: 2490,
    fabric: "80% cotton, 20% wool",
    fit: "Regular",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Sand", "Charcoal"],
    stock: 35,
    image: "images/men-soft-v-neck-knit.webp",
    description:
      "Soft V-Neck Knit brings a regular silhouette and considered texture to your everyday wardrobe. Made with 80% cotton, 20% wool, it pairs easily with your existing essentials.",
    care: "Wash gently according to the garment label. Use similar colours, reshape while damp, and dry in the shade. Tailored suits and waistcoats may require professional cleaning.",
    related: [
      "men-relaxed-knit-pullover",
      "men-cable-knit-cotton-sweater",
      "men-zip-neck-knit-pullover",
    ],
    imageWidth: 646,
    imageHeight: 383,
    styling:
      "Add texture over a simple base. Fold between wears to help retain shape.",
  },
  {
    id: "men-zip-neck-knit-pullover",
    name: "Zip-Neck Knit Pullover",
    gender: "Men",
    category: "Knitwear",
    price: 3290,
    fabric: "100% cotton",
    fit: "Relaxed",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Navy", "Taupe"],
    stock: 36,
    image: "images/men-zip-neck-knit-pullover.webp",
    description:
      "Zip-Neck Knit Pullover brings a relaxed silhouette and considered texture to your everyday wardrobe. Made with 100% cotton, it pairs easily with your existing essentials.",
    care: "Wash gently according to the garment label. Use similar colours, reshape while damp, and dry in the shade. Tailored suits and waistcoats may require professional cleaning.",
    related: [
      "men-relaxed-knit-pullover",
      "men-cable-knit-cotton-sweater",
      "men-soft-v-neck-knit",
    ],
    imageWidth: 646,
    imageHeight: 429,
    styling:
      "Add texture over a simple base. Fold between wears to help retain shape.",
  },
  {
    id: "men-everyday-training-joggers",
    name: "Everyday Training Joggers",
    gender: "Men",
    category: "Activewear",
    price: 1990,
    fabric: "85% polyester, 15% elastane",
    fit: "Athletic",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Charcoal", "Black"],
    stock: 37,
    image: "images/men-everyday-training-joggers.webp",
    description:
      "Everyday Training Joggers brings a athletic silhouette and considered texture to your everyday wardrobe. Made with 85% polyester, 15% elastane, it pairs easily with your existing essentials.",
    care: "Wash gently according to the garment label. Use similar colours, reshape while damp, and dry in the shade. Tailored suits and waistcoats may require professional cleaning.",
    related: [
      "men-performance-training-tee",
      "men-lightweight-training-shorts",
      "men-performance-zip-jacket",
    ],
    imageWidth: 646,
    imageHeight: 429,
    styling:
      "Combine with comfortable training separates and allow room for movement.",
  },
  {
    id: "men-lightweight-training-shorts",
    name: "Lightweight Training Shorts",
    gender: "Men",
    category: "Activewear",
    price: 1490,
    fabric: "90% polyester, 10% elastane",
    fit: "Athletic",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Blue", "Black"],
    stock: 18,
    image: "images/men-lightweight-training-shorts.webp",
    description:
      "Lightweight Training Shorts brings a athletic silhouette and considered texture to your everyday wardrobe. Made with 90% polyester, 10% elastane, it pairs easily with your existing essentials.",
    care: "Wash gently according to the garment label. Use similar colours, reshape while damp, and dry in the shade. Tailored suits and waistcoats may require professional cleaning.",
    related: [
      "men-performance-training-tee",
      "men-everyday-training-joggers",
      "men-performance-zip-jacket",
    ],
    imageWidth: 646,
    imageHeight: 406,
    styling:
      "Combine with comfortable training separates and allow room for movement.",
  },
  {
    id: "men-performance-zip-jacket",
    name: "Performance Zip Jacket",
    gender: "Men",
    category: "Activewear",
    price: 2790,
    fabric: "90% polyester, 10% elastane",
    fit: "Athletic",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Olive", "Black"],
    stock: 19,
    image: "images/men-performance-zip-jacket.webp",
    description:
      "Performance Zip Jacket brings a athletic silhouette and considered texture to your everyday wardrobe. Made with 90% polyester, 10% elastane, it pairs easily with your existing essentials.",
    care: "Wash gently according to the garment label. Use similar colours, reshape while damp, and dry in the shade. Tailored suits and waistcoats may require professional cleaning.",
    related: [
      "men-performance-training-tee",
      "men-everyday-training-joggers",
      "men-lightweight-training-shorts",
    ],
    imageWidth: 646,
    imageHeight: 406,
    styling:
      "Combine with comfortable training separates and allow room for movement.",
  },
  {
    id: "men-tailored-occasion-waistcoat",
    name: "Tailored Occasion Waistcoat",
    gender: "Men",
    category: "Formal wear",
    price: 2990,
    fabric: "70% polyester, 30% viscose",
    fit: "Tailored",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Sand", "Navy"],
    stock: 20,
    image: "images/men-tailored-occasion-waistcoat.webp",
    description:
      "Tailored Occasion Waistcoat brings a tailored silhouette and considered texture to your everyday wardrobe. Made with 70% polyester, 30% viscose, it pairs easily with your existing essentials.",
    care: "Wash gently according to the garment label. Use similar colours, reshape while damp, and dry in the shade. Tailored suits and waistcoats may require professional cleaning.",
    related: [
      "men-modern-tailored-blazer",
      "men-evening-formal-trousers",
      "men-modern-two-piece-suit",
    ],
    imageWidth: 656,
    imageHeight: 528,
    styling:
      "Choose clean layers for occasions. Check shoulders, waist, and garment length.",
  },
  {
    id: "men-modern-two-piece-suit",
    name: "Modern Two-Piece Suit",
    gender: "Men",
    category: "Formal wear",
    price: 7990,
    fabric: "70% polyester, 30% viscose",
    fit: "Tailored",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Navy", "Charcoal"],
    stock: 21,
    image: "images/men-modern-two-piece-suit.webp",
    description:
      "Modern Two-Piece Suit brings a tailored silhouette and considered texture to your everyday wardrobe. Made with 70% polyester, 30% viscose, it pairs easily with your existing essentials.",
    care: "Wash gently according to the garment label. Use similar colours, reshape while damp, and dry in the shade. Tailored suits and waistcoats may require professional cleaning.",
    related: [
      "men-modern-tailored-blazer",
      "men-evening-formal-trousers",
      "men-tailored-occasion-waistcoat",
    ],
    imageWidth: 656,
    imageHeight: 528,
    styling:
      "Choose clean layers for occasions. Check shoulders, waist, and garment length.",
  },
  {
    id: "women-floral-everyday-midi-dress",
    name: "Floral Everyday Midi Dress",
    gender: "Women",
    category: "Dresses",
    price: 3190,
    fabric: "100% viscose",
    fit: "Relaxed",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Taupe", "Rose"],
    stock: 22,
    image: "images/women-floral-everyday-midi-dress.webp",
    description:
      "Floral Everyday Midi Dress brings a relaxed silhouette and considered texture to your everyday wardrobe. Made with 100% viscose, it pairs easily with your existing essentials.",
    care: "Wash gently according to the garment label. Use similar colours, reshape while damp, and dry in the shade. Tailored suits and waistcoats may require professional cleaning.",
    related: [
      "women-everyday-midi-dress",
      "women-evening-satin-dress",
      "women-classic-wrap-dress",
    ],
    imageWidth: 656,
    imageHeight: 671,
    styling:
      "Wear simply for daytime or add a layer for evenings. Check bust, waist, and hip fit.",
  },
  {
    id: "women-classic-wrap-dress",
    name: "Classic Wrap Dress",
    gender: "Women",
    category: "Dresses",
    price: 2990,
    fabric: "100% viscose",
    fit: "Regular",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Rose"],
    stock: 23,
    image: "images/women-classic-wrap-dress.webp",
    description:
      "Classic Wrap Dress brings a regular silhouette and considered texture to your everyday wardrobe. Made with 100% viscose, it pairs easily with your existing essentials.",
    care: "Wash gently according to the garment label. Use similar colours, reshape while damp, and dry in the shade. Tailored suits and waistcoats may require professional cleaning.",
    related: [
      "women-everyday-midi-dress",
      "women-evening-satin-dress",
      "women-floral-everyday-midi-dress",
    ],
    imageWidth: 656,
    imageHeight: 671,
    styling:
      "Wear simply for daytime or add a layer for evenings. Check bust, waist, and hip fit.",
  },
  {
    id: "women-cotton-puff-sleeve-blouse",
    name: "Cotton Puff-Sleeve Blouse",
    gender: "Women",
    category: "Tops",
    price: 1990,
    fabric: "100% cotton",
    fit: "Regular",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Taupe", "Rose"],
    stock: 24,
    image: "images/women-cotton-puff-sleeve-blouse.webp",
    description:
      "Cotton Puff-Sleeve Blouse brings a regular silhouette and considered texture to your everyday wardrobe. Made with 100% cotton, it pairs easily with your existing essentials.",
    care: "Wash gently according to the garment label. Use similar colours, reshape while damp, and dry in the shade. Tailored suits and waistcoats may require professional cleaning.",
    related: [
      "women-soft-cotton-wrap-top",
      "women-soft-cotton-poplin-blouse",
      "women-essential-cotton-t-shirt",
    ],
    imageWidth: 512,
    imageHeight: 512,
    styling:
      "Pair with denim or tailored trousers for an adaptable combination.",
  },
  {
    id: "women-linen-weekend-co-ord",
    name: "Linen Weekend Co-ord",
    gender: "Women",
    category: "Co-ord sets",
    price: 3690,
    fabric: "100% linen",
    fit: "Relaxed",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Rose", "Sand"],
    stock: 25,
    image: "images/women-linen-weekend-co-ord.webp",
    description:
      "Linen Weekend Co-ord brings a relaxed silhouette and considered texture to your everyday wardrobe. Made with 100% linen, it pairs easily with your existing essentials.",
    care: "Wash gently according to the garment label. Use similar colours, reshape while damp, and dry in the shade. Tailored suits and waistcoats may require professional cleaning.",
    related: [
      "women-modern-linen-co-ord-set",
      "women-cotton-everyday-co-ord",
      "women-soft-knit-co-ord-set",
    ],
    imageWidth: 512,
    imageHeight: 512,
    styling:
      "Wear the pieces together, or combine each separate with wardrobe favourites.",
  },
  {
    id: "women-cotton-everyday-co-ord",
    name: "Cotton Everyday Co-ord",
    gender: "Women",
    category: "Co-ord sets",
    price: 3290,
    fabric: "100% cotton",
    fit: "Relaxed",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Olive", "Taupe"],
    stock: 26,
    image: "images/women-cotton-everyday-co-ord.webp",
    description:
      "Cotton Everyday Co-ord brings a relaxed silhouette and considered texture to your everyday wardrobe. Made with 100% cotton, it pairs easily with your existing essentials.",
    care: "Wash gently according to the garment label. Use similar colours, reshape while damp, and dry in the shade. Tailored suits and waistcoats may require professional cleaning.",
    related: [
      "women-modern-linen-co-ord-set",
      "women-linen-weekend-co-ord",
      "women-soft-knit-co-ord-set",
    ],
    imageWidth: 512,
    imageHeight: 512,
    styling:
      "Wear the pieces together, or combine each separate with wardrobe favourites.",
  },
  {
    id: "women-soft-knit-co-ord-set",
    name: "Soft Knit Co-ord Set",
    gender: "Women",
    category: "Co-ord sets",
    price: 4290,
    fabric: "100% cotton",
    fit: "Relaxed",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Taupe", "Sand"],
    stock: 27,
    image: "images/women-soft-knit-co-ord-set.webp",
    description:
      "Soft Knit Co-ord Set brings a relaxed silhouette and considered texture to your everyday wardrobe. Made with 100% cotton, it pairs easily with your existing essentials.",
    care: "Wash gently according to the garment label. Use similar colours, reshape while damp, and dry in the shade. Tailored suits and waistcoats may require professional cleaning.",
    related: [
      "women-modern-linen-co-ord-set",
      "women-linen-weekend-co-ord",
      "women-cotton-everyday-co-ord",
    ],
    imageWidth: 512,
    imageHeight: 512,
    styling:
      "Wear the pieces together, or combine each separate with wardrobe favourites.",
  },
  {
    id: "women-straight-leg-cotton-trousers",
    name: "Straight-Leg Cotton Trousers",
    gender: "Women",
    category: "Trousers",
    price: 2290,
    fabric: "98% cotton, 2% elastane",
    fit: "Straight",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Sand", "Black"],
    stock: 28,
    image: "images/women-straight-leg-cotton-trousers.webp",
    description:
      "Straight-Leg Cotton Trousers brings a straight silhouette and considered texture to your everyday wardrobe. Made with 98% cotton, 2% elastane, it pairs easily with your existing essentials.",
    care: "Wash gently according to the garment label. Use similar colours, reshape while damp, and dry in the shade. Tailored suits and waistcoats may require professional cleaning.",
    related: ["women-tailored-wide-leg-trousers"],
    imageWidth: 512,
    imageHeight: 512,
    styling:
      "Combine with a simple shirt or tucked top; check the seated waist fit.",
  },
  {
    id: "women-wide-leg-indigo-jeans",
    name: "Wide-Leg Indigo Jeans",
    gender: "Women",
    category: "Denim",
    price: 2790,
    fabric: "100% cotton denim",
    fit: "Wide leg",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Indigo", "Blue"],
    stock: 29,
    image: "images/women-wide-leg-indigo-jeans.webp",
    description:
      "Wide-Leg Indigo Jeans brings a wide leg silhouette and considered texture to your everyday wardrobe. Made with 100% cotton denim, it pairs easily with your existing essentials.",
    care: "Wash gently according to the garment label. Use similar colours, reshape while damp, and dry in the shade. Tailored suits and waistcoats may require professional cleaning.",
    related: ["women-high-rise-straight-jeans"],
    imageWidth: 512,
    imageHeight: 512,
    styling:
      "Combine with cotton basics and textured layers. Compare the rise and leg shape.",
  },
  {
    id: "women-embroidered-cotton-kurta",
    name: "Embroidered Cotton Kurta",
    gender: "Women",
    category: "Ethnic wear",
    price: 2490,
    fabric: "100% cotton",
    fit: "Relaxed",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Rose", "Taupe"],
    stock: 30,
    image: "images/women-embroidered-cotton-kurta.webp",
    description:
      "Embroidered Cotton Kurta brings a relaxed silhouette and considered texture to your everyday wardrobe. Made with 100% cotton, it pairs easily with your existing essentials.",
    care: "Wash gently according to the garment label. Use similar colours, reshape while damp, and dry in the shade. Tailored suits and waistcoats may require professional cleaning.",
    related: [
      "women-printed-everyday-kurta",
      "women-classic-straight-kurta",
      "women-sage-printed-kurta",
    ],
    imageWidth: 512,
    imageHeight: 512,
    styling: "Pair with comfortable trousers and understated accessories.",
  },
  {
    id: "women-classic-straight-kurta",
    name: "Classic Straight Kurta",
    gender: "Women",
    category: "Ethnic wear",
    price: 2190,
    fabric: "100% cotton",
    fit: "Straight",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Taupe", "Sand"],
    stock: 31,
    image: "images/women-classic-straight-kurta.webp",
    description:
      "Classic Straight Kurta brings a straight silhouette and considered texture to your everyday wardrobe. Made with 100% cotton, it pairs easily with your existing essentials.",
    care: "Wash gently according to the garment label. Use similar colours, reshape while damp, and dry in the shade. Tailored suits and waistcoats may require professional cleaning.",
    related: [
      "women-printed-everyday-kurta",
      "women-embroidered-cotton-kurta",
      "women-sage-printed-kurta",
    ],
    imageWidth: 512,
    imageHeight: 512,
    styling: "Pair with comfortable trousers and understated accessories.",
  },
  {
    id: "women-sage-printed-kurta",
    name: "Sage Printed Kurta",
    gender: "Women",
    category: "Ethnic wear",
    price: 2290,
    fabric: "100% cotton",
    fit: "Relaxed",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Sage", "Taupe"],
    stock: 32,
    image: "images/women-sage-printed-kurta.webp",
    description:
      "Sage Printed Kurta brings a relaxed silhouette and considered texture to your everyday wardrobe. Made with 100% cotton, it pairs easily with your existing essentials.",
    care: "Wash gently according to the garment label. Use similar colours, reshape while damp, and dry in the shade. Tailored suits and waistcoats may require professional cleaning.",
    related: [
      "women-printed-everyday-kurta",
      "women-embroidered-cotton-kurta",
      "women-classic-straight-kurta",
    ],
    imageWidth: 512,
    imageHeight: 512,
    styling: "Pair with comfortable trousers and understated accessories.",
  },
  {
    id: "women-cable-knit-cardigan",
    name: "Cable-Knit Cardigan",
    gender: "Women",
    category: "Knitwear",
    price: 3190,
    fabric: "100% cotton",
    fit: "Relaxed",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Taupe", "Sand"],
    stock: 33,
    image: "images/women-cable-knit-cardigan.webp",
    description:
      "Cable-Knit Cardigan brings a relaxed silhouette and considered texture to your everyday wardrobe. Made with 100% cotton, it pairs easily with your existing essentials.",
    care: "Wash gently according to the garment label. Use similar colours, reshape while damp, and dry in the shade. Tailored suits and waistcoats may require professional cleaning.",
    related: [
      "women-relaxed-knit-cardigan",
      "women-soft-ribbed-sweater",
      "women-soft-sleeveless-knit-vest",
    ],
    imageWidth: 512,
    imageHeight: 512,
    styling:
      "Add texture over a simple base. Fold between wears to help retain shape.",
  },
  {
    id: "women-soft-sleeveless-knit-vest",
    name: "Soft Sleeveless Knit Vest",
    gender: "Women",
    category: "Knitwear",
    price: 1890,
    fabric: "80% cotton, 20% wool",
    fit: "Regular",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Sand", "Charcoal"],
    stock: 34,
    image: "images/women-soft-sleeveless-knit-vest.webp",
    description:
      "Soft Sleeveless Knit Vest brings a regular silhouette and considered texture to your everyday wardrobe. Made with 80% cotton, 20% wool, it pairs easily with your existing essentials.",
    care: "Wash gently according to the garment label. Use similar colours, reshape while damp, and dry in the shade. Tailored suits and waistcoats may require professional cleaning.",
    related: [
      "women-relaxed-knit-cardigan",
      "women-soft-ribbed-sweater",
      "women-cable-knit-cardigan",
    ],
    imageWidth: 512,
    imageHeight: 512,
    styling:
      "Add texture over a simple base. Fold between wears to help retain shape.",
  },
  {
    id: "women-lightweight-training-jacket",
    name: "Lightweight Training Jacket",
    gender: "Women",
    category: "Activewear",
    price: 2490,
    fabric: "90% polyester, 10% elastane",
    fit: "Athletic",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Sage", "Black"],
    stock: 35,
    image: "images/women-lightweight-training-jacket.webp",
    description:
      "Lightweight Training Jacket brings a athletic silhouette and considered texture to your everyday wardrobe. Made with 90% polyester, 10% elastane, it pairs easily with your existing essentials.",
    care: "Wash gently according to the garment label. Use similar colours, reshape while damp, and dry in the shade. Tailored suits and waistcoats may require professional cleaning.",
    related: [
      "women-everyday-active-leggings",
      "women-soft-performance-training-tee",
      "women-everyday-training-joggers",
    ],
    imageWidth: 512,
    imageHeight: 512,
    styling:
      "Combine with comfortable training separates and allow room for movement.",
  },
  {
    id: "women-soft-performance-training-tee",
    name: "Soft Performance Training Tee",
    gender: "Women",
    category: "Activewear",
    price: 1290,
    fabric: "90% polyester, 10% elastane",
    fit: "Athletic",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Rose", "Black"],
    stock: 36,
    image: "images/women-soft-performance-training-tee.webp",
    description:
      "Soft Performance Training Tee brings a athletic silhouette and considered texture to your everyday wardrobe. Made with 90% polyester, 10% elastane, it pairs easily with your existing essentials.",
    care: "Wash gently according to the garment label. Use similar colours, reshape while damp, and dry in the shade. Tailored suits and waistcoats may require professional cleaning.",
    related: [
      "women-everyday-active-leggings",
      "women-lightweight-training-jacket",
      "women-everyday-training-joggers",
    ],
    imageWidth: 640,
    imageHeight: 599,
    styling:
      "Combine with comfortable training separates and allow room for movement.",
  },
  {
    id: "women-everyday-training-joggers",
    name: "Everyday Training Joggers",
    gender: "Women",
    category: "Activewear",
    price: 2190,
    fabric: "85% polyester, 15% elastane",
    fit: "Relaxed",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Charcoal", "Black"],
    stock: 37,
    image: "images/women-everyday-training-joggers.webp",
    description:
      "Everyday Training Joggers brings a relaxed silhouette and considered texture to your everyday wardrobe. Made with 85% polyester, 15% elastane, it pairs easily with your existing essentials.",
    care: "Wash gently according to the garment label. Use similar colours, reshape while damp, and dry in the shade. Tailored suits and waistcoats may require professional cleaning.",
    related: [
      "women-everyday-active-leggings",
      "women-lightweight-training-jacket",
      "women-soft-performance-training-tee",
    ],
    imageWidth: 638,
    imageHeight: 599,
    styling:
      "Combine with comfortable training separates and allow room for movement.",
  },
  {
  "id": "men-smart-oxford-shirt",
  "name": "Smart Oxford Shirt",
  "category": "Shirts",
  "price": 2190,
  "fabric": "100% cotton",
  "fit": "Regular",
  "colors": [
    "Blue"
  ],
  "image": "images/men-oxford-cotton-shirt.webp",
  "styling": "Pair with tailored trousers for work or denim for relaxed weekends.",
  "gender": "Men",
  "sizes": [
    "S",
    "M",
    "L",
    "XL",
    "XXL"
  ],
  "stock": 20,
  "description": "Smart Oxford Shirt offers a regular fit. Pair with tailored trousers for work or denim for relaxed weekends.",
  "care": "Follow the garment care label. Wash with similar colours and dry in the shade; professionally clean tailored blazers.",
  "related": [
    "men-modern-two-piece-suit",
    "mens-cotton-shirt",
    "men-tailored-straight-fit-trousers"
  ]
},
  {
  "id": "men-blue-occasion-blazer",
  "name": "Blue Occasion Blazer",
  "category": "Formal wear",
  "price": 5290,
  "fabric": "70% polyester, 30% viscose",
  "fit": "Tailored",
  "colors": [
    "Blue"
  ],
  "image": "images/men-modern-blazer-blue.webp",
  "styling": "Layer over a crisp shirt for occasions. Check the shoulder and sleeve fit.",
  "gender": "Men",
  "sizes": [
    "S",
    "M",
    "L",
    "XL",
    "XXL"
  ],
  "stock": 20,
  "description": "Blue Occasion Blazer offers a tailored fit. Layer over a crisp shirt for occasions. Check the shoulder and sleeve fit.",
  "care": "Follow the garment care label. Wash with similar colours and dry in the shade; professionally clean tailored blazers.",
  "related": [
    "men-modern-two-piece-suit",
    "mens-cotton-shirt",
    "men-tailored-straight-fit-trousers"
  ]
},
  {
  "id": "men-weekend-cotton-chinos",
  "name": "Weekend Cotton Chinos",
  "category": "Trousers",
  "price": 2490,
  "fabric": "98% cotton, 2% elastane",
  "fit": "Relaxed",
  "colors": [
    "Sand"
  ],
  "image": "images/men-relaxed-weekend-chinos.webp",
  "styling": "Wear with a cotton shirt or polo for comfortable everyday dressing.",
  "gender": "Men",
  "sizes": [
    "S",
    "M",
    "L",
    "XL",
    "XXL"
  ],
  "stock": 20,
  "description": "Weekend Cotton Chinos offers a relaxed fit. Wear with a cotton shirt or polo for comfortable everyday dressing.",
  "care": "Follow the garment care label. Wash with similar colours and dry in the shade; professionally clean tailored blazers.",
  "related": [
    "men-modern-two-piece-suit",
    "mens-cotton-shirt",
    "men-tailored-straight-fit-trousers"
  ]
},
];
